name: Actions Workflow
on: 
  repository_dispatch:
    types: [build]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: | 
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files after checkout
        run: | 
          pwd
          ls -al
      - name: JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Lionel
      - name: Log Greeting Time
        run: echo the current time is "${{ steps.greet.outputs.time }}"