name: Docker Demos
on: push
jobs:
  docker-containers-in-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16.15.1-alpine3.16
    steps:
      - name: Log node with Jessie
        run: node -v
      - name: Run hello world with docker image
        uses: docker://node:16.15.1-alpine3.16
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log node version with Alpine
        uses: docker://node:16.15.1-alpine3.16
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Show Repo Files
        run: |
          ls -al
          cat ./hello.sh
      - name: Execute shell script
        uses: docker://node:16.15.1-alpine3.16
        with:
          entrypoint: ./hello.sh
          args: "Lionel"
      - name: Send Slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "This is a slack message from a GitHub action"
  node-with-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Create user
        run: 'curl -X POST http://localhost:3001/api/user
          -H ''Content-Type: application/json''
          -d ''{"username": "hello", "address": "14137 aldkfdj"}'''
      - name: Get users
        run: curl http://localhost:3001/api/users
