name: Docker Demos
on: push
jobs:
  node-with-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Create user
        run: 'curl -X POST http://localhost:3001/api/user
          -H ''Content-Type: application/json''
          -d ''{"username": "hello", "address": "14137 aldkfdj"}'''
      - name: Get users
        run: curl http://localhost:3001/api/users
