name: Shell Commands
on: [push]
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: say hello world
        run: echo "Hello World"
      - name: node and nmp versions
        run: |
          node -v 
          npm -v